const $=id=>document.getElementById(id);let file=null,resultUrl=null,painting=false;
$("browse").onclick=()=>$("fileInput").click();$("dropzone").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>setFile(e.target.files[0]);
function setFile(f){if(!f||!f.type.startsWith('image/'))return;file=f;const r=new FileReader();r.onload=()=>{$("inputPreview").src=r.result;$('inputPreviewWrap').classList.remove('hidden');$('dropzone').classList.add('hidden');$('fileName').textContent=f.name;setTimeout(resizeCanvas,30)};r.readAsDataURL(f);$('message').textContent='Tô vùng caliper trên ảnh rồi bấm xử lý.'}
function resizeCanvas(){const c=$('maskCanvas'),b=c.getBoundingClientRect();c.width=b.width*devicePixelRatio;c.height=b.height*devicePixelRatio;const x=c.getContext('2d');x.scale(devicePixelRatio,devicePixelRatio);x.lineWidth=14;x.lineCap='round';x.strokeStyle='#fff'}
function point(e){const r=$('maskCanvas').getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
$('maskCanvas').onpointerdown=e=>{painting=true;const p=point(e),x=$('maskCanvas').getContext('2d');x.beginPath();x.moveTo(p.x,p.y)};$('maskCanvas').onpointermove=e=>{if(!painting)return;const p=point(e),x=$('maskCanvas').getContext('2d');x.lineTo(p.x,p.y);x.stroke()};window.onpointerup=()=>painting=false;
$('clearMask').onclick=()=>{const c=$('maskCanvas');c.getContext('2d').clearRect(0,0,c.width,c.height)};$('removeFile').onclick=()=>{file=null;$('inputPreviewWrap').classList.add('hidden');$('dropzone').classList.remove('hidden');$('fileInput').value=''};
function maskBlob(){const c=$('maskCanvas'),tmp=document.createElement('canvas');tmp.width=$('inputPreview').naturalWidth;tmp.height=$('inputPreview').naturalHeight;const x=tmp.getContext('2d');x.fillStyle='black';x.fillRect(0,0,tmp.width,tmp.height);x.drawImage(c,0,0,tmp.width,tmp.height);return new Promise(ok=>tmp.toBlob(ok,'image/png'))}
$("processBtn").onclick=async()=>{if(!file){$('message').textContent='Vui lòng chọn ảnh.';return}const btn=$('processBtn');btn.disabled=true;$('outputTag').textContent='PROCESSING';$('message').textContent='LaMa đang xử lý mask…';try{const form=new FormData();form.append('image',file);form.append('mask',await maskBlob(),'mask.png');const res=await fetch('http://127.0.0.1:8000/inpaint',{method:'POST',body:form});if(!res.ok)throw new Error((await res.json()).detail||'Không kết nối được LaMa backend');const blob=await res.blob();resultUrl=URL.createObjectURL(blob);$('outputPreview').src=resultUrl;$('outputPreview').classList.remove('hidden');document.querySelector('.result-placeholder').classList.add('hidden');$('downloadBtn').classList.remove('hidden');$('outputTag').textContent='DONE';$('message').textContent='Đã xử lý xong.'}catch(e){$('outputTag').textContent='ERROR';$('message').textContent=e.message}finally{btn.disabled=false}};$('downloadBtn').onclick=()=>{const a=document.createElement('a');a.href=resultUrl;a.download='caliper-cleaned.png';a.click()};
